name: S3 Deploy
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      VITE_PB_URL: ${{ secrets.VITE_PB_URL}}
      VITE_DISCORD_WEBHOOK_URL: ${{secrets.VITE_DISCORD_WEBHOOK_URL}}
      VITE_DISCORD_CHANNEL_ID: ${{secrets.VITE_DISCORD_CHANNEL_ID}}
    steps:
        - uses: actions/checkout@v3

        - name: Install dependencies
          run: npm install

        - name: Build
          run: npm run build

        - name: Deploy
          uses: reggionick/s3-deploy@v3
          with:
            folder: dist
            bucket: ${{ secrets.S3_BUCKET }}
            bucket-region: ${{ secrets.S3_BUCKET_REGION }}
            dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
            invalidation: /
            delete-removed: true
            no-cache: false
            private: false
            filesToInclude: ".*/*,*/*,**"